[package]
name = "chRUSTmas"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.15", features = ["serde"] }
num-integer = "0.1.46"
polars = { version = "0.44.0", features = ["lazy", "csv", "ndarray"] }
rand = "0.9.2"
